project:
  type: website
output-dir: docs
website:
  title: "Edgar's_blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create docs directory
        run: mkdir -p docs
      - name: Build site
        uses: actions/jekyll-build-pages@v1.0.13
